### PR TITLE
Heavily change the bookmarks example

### PR DESCRIPTION
**Pull request by bdejong**
@ffont @spookyUnknownUser have a look. I refactored the bookmark example heavily...

### CODE REVIEW

**Comment by spookyUnknownUser** [comment]
Woah that is so much simpler!

**Comment by spookyUnknownUser** [comment]
also, what are the benefits of setting the access token as an environmental variable?

**Comment by ffont** [comment]
Hi,

I merged the pull request and added a missing 'sys' import (see https://github.com/MTG/freesound-python/commit/9dba8cce7bc6e6d4344fee4972fa564bbd5d414e).

The pager however is not working ok. Once the next parameter is not present it seems to break when calling next_page(). 

Also because it is trying to download all bookmarks from my user (and I have a significant number of long files), it takes a lot of time to finish the example. You can change "frederic.font" for "apitest", which only has 4 bookmarks (2 uncategorised and 2 with a category).

**Comment by bdejong** [comment]
Hmm, @ffont do you have any idea how to write a better:

```
while something(page):
   for item in page:
       ...
   page = page.next()
```

**Comment by ffont** [comment]
hmmm I see it is not trivial... maybe just break while if (after for item in page) pager has no next, else do page=page.next()
Maybe this is what was implemented in previous versions I'm not sure...
Or maybe we could turn the pager itself into an iterable which handles all this internally. That would be cool but I'm not sure how easy would that be.

**Comment by bdejong** [comment]
Ah, true, so...

```python
while True:
    for item in pager:
        pass
    if not pager.has_next:
        break
    pager = pager.next
```

**Comment by bdejong** [comment]
Fixed the example and used the new bookmark.id field:

https://github.com/MTG/freesound-python/blob/master/download_bookmarks_example.py#L36

**Pull request merged**
