### PR TITLE
[WIP] Added the Black Python code formatter to run as linting

### PR DESCRIPTION
**Pull request by bdejong**
Added the Black Python code formatter to run as linting

### CODE REVIEW

**Comment by bdejong** [comment]
@ffont I thought this could be a useful step in the build process, but for some reason the secret failed in the example runner... 🤔 any ideas if I broke something?

**Comment by ffont** [comment]
Hi @bdejong!
Great to see a PR!
Hmm it looks like the auto-formatting broke something? Are you able to run the `examples.py` locally?

**Comment by bdejong** [comment]
@ffont  Runs just fine:

```
  ➔ export FREESOUND_API_KEY="Natt59mWhDp<snip>idUZ6FeZxhd"
  ➔ python examples.py
  Sound info:
  -----------
  Getting sound: coming soon.wav
  Url: https://freesound.org/people/tim.kahn/sounds/96541/
  Description: For the user "Stealth Inc.", my girlfriend saying "Coming soon". Recorded with an AT2020 microphone into an Apogee Duet and edited with Record.
  Tags: request female girl talk vocal voice american woman english speak
  
  Sound info specifying some request parameters:
  <snip>
```

I think it's something to do with the github secrets... Do I need a specific API token to run the github examples? I'm using an API key which is as old as the dinosaurs, maybe that could be it?

**Comment by bdejong** [comment]
@ffont found it. It must be a specific API token problem as the example fails AFTER getting the token from the environmental variables:

https://github.com/MTG/freesound-python/actions/runs/5643202742/job/15284559728#step:5:14

Could you tell me how you created the token which is stored in the secrets?

**Comment by ffont** [comment]
Hmmm if your API key works locally it should also work in the github action (even if it is as old as dinosaurs). Is it correctly set as a "Repository secret" with the name `FREESOUND_API_KEY` under the secrets tab? (without any "environment secrets")

**Pull request closed without merging**
