### PR TITLE
Examples for Python 3

### PR DESCRIPTION
**Pull request by Canule**

### CODE REVIEW

**Comment by alastair** [comment]
What changes did you make for this example file? If the only difference is the print function then we should be able to use `from __future__ import print_function` in the normal example file and it will continue to work in both python2 and 3

**Comment by Canule** [comment]
I wasn't aware of the from __future__ import print_function.
No changes made.

**Comment by ffont** [comment]
Then as I understand the changes to be made are to use print() function in [current examples file](https://github.com/MTG/freesound-python/blob/master/examples.py) and import from future right? (instead of adding a new examples py3 file).
@Canule are you willing to do this? If you update pull request with these changes then we can accept it.

Thanks!

**Comment by ffont** [comment]
Hi,
I've seen the new commit but I guess I was not clear in the last message. As I see now you basically deleted all your changes right?
What we meant is that to make examples py3 and py2 compatible you needed to use `print(xyz)` instead of `print xyz`,   and also import print function from future. These changes should be in examples.py file which will be the same for py2 and py3.

Cheers,

**Pull request merged**
