### PR TITLE
Create a summary of how to connect to oauth

### PR DESCRIPTION
**Pull request by spookyUnknownUser**
The freesound library makes many references to a manual workflow in creating oauth api uses. Hopefully this will give others more direction in how to approach the workflow. I was kinda confused, got mixed up with tokens a couple times.

### CODE REVIEW

**Comment by ffont** [comment]
Hi spookyUnknownUser,

Let me first thank you for your contribution.
The clarification to the oauth process you propose however is already explained in detail in the official Freesound API documentation (http://www.freesound.org/docs/api/authentication.html), therefore there is no need to duplicate content here (it will make it harder to maintain).
I'll add a link in the readme to this particular documentation section nevertheless.

Cheers,

frederic

**Comment by spookyUnknownUser** [comment]
Ah thanks!

Do you think I could add the "download all bookmarks" into examples, then?

**Comment by ffont** [comment]
Yes, although you should add the comment that clearly states that this requires oauth.
Regarding the comment of knowing for how long you should get next pages, the returned json has a next and previous field that you could use to check. Next will be null if there are no more sounds/bookmarks.

**Comment by spookyUnknownUser** [comment]
Great, I'll make those changes

**Pull request closed without merging**
